version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
      - azurite
    environment:
      # PostgreSQL Metadata
      POSTGRES_METADATA_CONNECTION: "Host=postgres;Port=5432;Database=metadata_db;Username=postgres;Password=pass"

      # PostgreSQL Chunk
      POSTGRES_CHUNK_CONNECTION: "Host=postgres;Port=5432;Database=chunk_db;Username=postgres;Password=pass"

      # Redis
      REDIS_CONNECTION: "redis:6379"

      # Azure Blob via Azurite
      AZURE_CONNECTION: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vd...==;BlobEndpoint=http://azurite:10000/devstoreaccount1;"
      AZURE_CONTAINER: "chunks"

    ports:
      - "8080:80"
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/data
    command: "azurite-blob --blobHost 0.0.0.0"

volumes:
  pgdata:
  azurite_data:
