// <auto-generated />
using DistributedFileStorage.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DistributedFileStorage.Infrastructure.Migrations.ChunkDb
{
    [DbContext(typeof(PostgreChunkDbContext))]
    [Migration("20250727131614_InitChunkDb")]
    partial class InitChunkDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DistributedFileStorage.Infrastructure.Persistence.PostgreStoredChunk", b =>
                {
                    b.Property<string>("ChunkId")
                        .HasColumnType("text");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("ChunkId");

                    b.ToTable("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
